### ISSUE TITLE
Some question about the code

### ISSUE THREAD

**Issue by michael0703** [nairouz/R-GAE#3]
Hi, recently I am studying the attributed network clustering topic, and I found your repo.
And I have some question about the code
1. After I install all the requirements, I successfully run the code with "python xxxxx/main_cora.py"，but the model finish training at a very short period, and I lookup in the code and see that the training epoch is 200, so the question is, the model you proposed needs only 200 epochs to train from scratch (or pretraining) to convergence ? or the epoch = 200 is only a sample for people to understand.
2. I would really like to further discuss with you about this topic, so if its possible that we can communicate through email? It would really help me a lot! my email is : liaoweiskewer0703@gmail.com

Thanks a lot!

**Comment by nairouz** [comment]
Hi,

Thanks for your interest. You can email me your questions and I will respond as soon as possible. I will now close since this not really an issue.
